### ISSUE TITLE
How to download images for training?

### ISSUE THREAD

**Issue by dawoodwasif** [HongguLiu/Deepfake-Detection#31]
The text file you mentioned has a list of image paths and labels. However, the FaceForensics++ dataset only has videos. How do you obtain these images?

**Comment by HongguLiu** [comment]
We use two ways to obtain face from videos:
1. python lib: dlib
2. [RetinaFace](https://github.com/biubug6/Pytorch_Retinaface)

Both can detect the faces from images.

**Comment by dawoodwasif** [comment]
Thanks for the reply. However, I am talking about the images that are sampled from the video. Do you extract images from each video and then extract the faces?

**Comment by HongguLiu** [comment]
yes.
you can use cv2 to read the video, and extract the frames.
