### ISSUE TITLE
Do i need cuda to run test_CNN.py?

### ISSUE THREAD

**Issue by julschoy** [HongguLiu/Deepfake-Detection#9]
I have installed all the requirements but i am running CPU insteaad of GPU and i cant seem to get test_CNN.py to run.

**Comment by HongguLiu** [comment]
if you want to run this code on CPU, you must replace `model = model.cuda  image = image.cuda() labels = labels.cuda()` with `model = model.cpu()  image = image.cpu() labels = labels.cpu()`

**Comment by julschoy** [comment]
omg thanks!! hahah i am new in this field and i will try it again later!
